### ISSUE TITLE
Secret doors

### ISSUE THREAD

**Issue by mefgengus** [Bouncyrock/TaleSpire-Beta-AssetRequests#140] opened 2020-11-25 08:49 UTC
**Describe the Asset**
What does it look like, how is it used. Paint us a figurative picture.

Ok sorry I know it’s been done,,...how about a book case door but opens like the other doors and is put with the other book cases....large tapestry that drops away but covers a large wall area hiding a door...new statue that can be slid aside....and doors that look like wall sections..but slot into a normal door openings....maybe with a slight magical blurr
**Examples (images, videos, something which gets the point across**
Or show us a literal picture. That works too.

**Additional context**
Unburden yourself of thoughts and musings here
What will be will be love it all..thanks

-- Leave this next line for others to see --
** ADD :thumbsup:[thumbs up reaction] to give this request more attention.**

**Comment by LuPro** [comment] 2020-11-28 18:27
Duplicate of #5

**Closed by LuPro** 2020-11-28 18:27 UTC
