### ISSUE TITLE
Dungeon traps; trick wall/floor, elemental animation

### ISSUE THREAD

**Issue by sneekyfox** [Bouncyrock/TaleSpire-Beta-AssetRequests#122] opened 2020-08-06 04:44 UTC
A wall and floor sets that looks normal, but then when toggled by the GM/player they crumble apart, slide, or disappear. Another classic would be a bookshelf that can do this too..

A single strip (wall thin) and a 1×1 tile that can be placed into a floor or wall, or in the same space as a chest or box, that you can then set to have an element pop out of it, like smoke (poison gas) a gout of flame, spikes, or an arc of lightning (maybe even arrows?). The trigger either GM controlled or (maybe) play in cinematic mode. 

 
![38f54fbf2b9ab1a31c08df3960126bbf](https://user-images.githubusercontent.com/69286824/89491674-c5583e80-d77d-11ea-8aeb-7d8d6bc63c27.jpg)

![traps1](https://user-images.githubusercontent.com/69286824/89491246-cc328180-d77c-11ea-8a02-cf833dc3fdea.jpg)

![81e544_6234853](https://user-images.githubusercontent.com/69286824/89491255-d18fcc00-d77c-11ea-8051-a5e2dc243085.jpg)

![images](https://user-images.githubusercontent.com/69286824/89491261-d94f7080-d77c-11ea-8ea0-f0c2f67ffd4b.jpeg)

**Additional context**
These would be good for traps, secret rooms or puzzles and for if we want to use it in a cut scene for story. (You could even use the flames or gas to enhance a volcanic environment) 

** ADD :thumbsup:[thumbs up reaction] to give this request more attention.**

**Comment by LuPro** [comment] 2020-11-28 18:24
Duplicate of / addition to #5

**Closed by LuPro** 2020-11-28 18:24 UTC
