### ISSUE TITLE
Modular deciduous tree (trunk and leaves as two separate entities)

### ISSUE THREAD

**Issue by Roxfall** [Bouncyrock/TaleSpire-Beta-AssetRequests#81] opened 2020-05-18 15:51 UTC
**Describe the Asset**
We have a small tree already. Could we get a separate asset for just the foliage without the trunk, so we can stack in arbitrarily large patterns?

Having a variety of sizes of trunks would be nice too, but we can use the trunks we already have in the game in a pinch.

**Examples (images, videos, something which gets the point across**
Just take the small deciduous tree already in the game, and cut the bottom half off.

Here's an example of multi-tree builds with existing assets. Those trunks at the bottom make this process very hard, and the things come out a bit lumpy. https://talesbazaar.com/prefab/960

**Additional context**
The bush we have (2x1) is too rectangular and unnatural looking to be used as intended, I've been sinking the deciuous tree into the ground for more "wild" looking bushes. I love that tree and I wish there was more of it. Would be nice to have various sizes of it too.

-- Leave this next line for others to see --
** ADD :thumbsup:[thumbs up reaction] to give this request more attention.**

**Comment by LuPro** [comment] 2020-12-22 02:58
Just noticed this is a duplicate of #73 - great detail in the description though :)

**Closed by LuPro** 2020-12-22 02:58 UTC
Labels: Tiles
