### ISSUE TITLE
Crops (corn and various plants)

### ISSUE THREAD

**Issue by Istallri** [Bouncyrock/TaleSpire-Beta-AssetRequests#100] opened 2020-06-18 16:48 UTC
**Describe the Asset**
Crops from various plants, would be 'non physcial' or traversable by figurines
Perhaps different growth levels too

**Examples (images, videos, something which gets the point across**
Or show us a literal picture. That works too.
![image](https://user-images.githubusercontent.com/65011758/85048846-2e670100-b194-11ea-9e6f-dd2b3803ed52.png)
![image](https://user-images.githubusercontent.com/65011758/85048911-45a5ee80-b194-11ea-8970-436c5bdbb3d0.png)

-- Leave this next line for others to see --
** ADD :thumbsup:[thumbs up reaction] to give this request more attention.**

**Comment by LuPro** [comment] 2020-06-19 14:36
Duplicate of #30

**Closed by LuPro** 2020-06-19 14:36 UTC
