### ISSUE TITLE
Dirt path 2x2 without green corners and 1x1 without corners

### ISSUE THREAD

**Issue by Roxfall** [Bouncyrock/TaleSpire-Beta-AssetRequests#133] opened 2020-10-27 15:00 UTC
**Describe the Asset**
It's complicated to make a 1x1 forest path using 2x2 tiles, and some of the larger dirt road intersections (3x3+) without having green corners. Thus it would be good to have a 2x2 tile that doesn't have green corners and a 1x1 tile that also doesn't have them.

**Examples (images, videos, something which gets the point across**
Or show us a literal picture. That works too.

**Additional context**
Unburden yourself of thoughts and musings here

-- Leave this next line for others to see --
** ADD :thumbsup:[thumbs up reaction] to give this request more attention.**

**Comment by LuPro** [comment] 2020-10-27 15:18
Duplicate of #6 (in there tiles for wider roads were requested)

**Closed by LuPro** 2020-10-27 15:18 UTC
